GET http://localhost:5000/users/id/transactions?limit=8&offset=0
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJjcmVhdGl2ZWZuIiwidXNlcklkIjoyLCJyb2xlIjoiY3JlYXRvciIsImxhc3ROYW1lIjoiY3JlYXRpdmVsbiIsImF2YXRhciI6ImFub24ucG5nIiwiZGlzcGxheU5hbWUiOiJjcmVhdGl2ZWRuIiwiYmFsYW5jZSI6IjEwMCIsImVtYWlsIjoiY3JlYXRpdmVAZ21haWwuY29tIiwicmF0aW5nIjowLCJpYXQiOjE3MzIzNzY1MTQsImV4cCI6MTczMjM4MDExNH0.XiWiYGvp7xUR19eAd2DQjrYjGS0uOeAJTa9bkZ9Q2gw